version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    depends_on:
      - gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  gateway:
    build: ./gateway
    env_file: ./gateway/.env
    ports:
      - "8000:8000"
    depends_on:
      - auth

  auth:
    build: ./auth
    env_file: ./auth/.env
    depends_on:
      - postgres
    volumes:
      - ./auth/app:/app/app
      - ./auth/alembic:/app/alembic
      - ./auth/alembic.ini:/app/alembic.ini

volumes:
  pgdata:
