version: "3.9"

services:
  postgresAuth:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_auth
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    depends_on:
      - gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  gateway:
    build: ./gateway
    env_file: ./gateway/.env
    ports:
      - "8000:8000"
    depends_on:
      - auth

  auth:
    build: ./auth
    env_file: ./auth/.env
    depends_on:
      - postgresAuth
    volumes:
      - ./auth/app:/app/app
      - ./auth/alembic:/app/alembic
      - ./auth/alembic.ini:/app/alembic.ini

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  
  postgresScraper:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_scrapercatalog
    ports:
      - "5434:5432"
    volumes:
      - pgdata-scraper:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  scraper:
    build: ./scraper
    env_file: ./scraper/.env
    depends_on: [redis, scrapercatalog]
    # ports: ["8002:8000"]  # внешний порт/внутренний порт

  scrapercatalog:
    build: ./scraperCatalog
    env_file: ./scraperCatalog/.env
    depends_on: 
      - postgresScraper
    # ports: ["8003:8000"]
    volumes:
      - ./scraperCatalog/app:/app/app
      - ./scraperCatalog/alembic:/app/alembic
      - ./scraperCatalog/alembic.ini:/app/alembic.ini

  catalog:
    build: ./catalog
    env_file: ./catalog/.env
    depends_on:
      - scrapercatalog
    # ports: ["8001:8000"]
    volumes:
      - ./catalog/app:/app/app
      - ./scraperCatalog/app/photos:/app/photos:ro

volumes:
  pgdata:
  pgdata-scraper:
